name: Daily Real Estate News

on:
  schedule:
    - cron: '30 22 * * *'
  workflow_dispatch:

jobs:
  collect-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install anthropic requests beautifulsoup4 lxml python-dateutil feedparser
        
    - name: Run news collection script
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: python collect_news.py
      
    - name: Upload results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: daily-news-${{ github.run_number }}
        path: news_output.md
